### ISSUE TITLE
Login form-Admin-app - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-3#2]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend
- 
![image](https://user-images.githubusercontent.com/35475543/221019221-e0ef4eef-4185-444c-99e2-b5d615a16fe9.png)

**Comment by Esther-Wavinya** [comment]
I want to do this.

**Comment by Esther-Wavinya** [comment]
Can I also get the figma link to the project please?

**Comment by peculiaruc** [comment]
Kindly read the README.md. The are there

**Comment by adeniranjohn** [comment]
@dekunleroy Please work with @Esther-Wavinya on this. I am wondering why I can't assign you to this task.

**Comment by Esther-Wavinya** [comment]
I am having access rights problems unable to push changes..

The eroor is ERROR: Permission to ALCOpenSource/Mentor-Management-System-Team-3.git denied to Esther-Wavinya.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by dekunleroy** [comment]
> I am having access rights problems unable to push changes..
> 
> The eroor is ERROR: Permission to ALCOpenSource/Mentor-Management-System-Team-3.git denied to Esther-Wavinya.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Ideally you shouldn't be experiencing this if you've been invited to this repo.

Nevertheless, you can try the following:

Create a fork of this repo and copy the origin url.

In the terminal of your workspace you can run the following: git remote set-url origin "origin-url-of-the-forked-repo-here"

Once done, you can push and create a PR. against the develop branch of this repo
