### ISSUE TITLE
Profile-Admin-app - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-3#5]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221151634-6d13fdaf-2e86-470c-a840-da4bcd6188b6.png)

**Comment by dekunleroy** [comment]
I'll be picking this up.

cc: @peculiaruc 
@adeniranjohn

**Comment by peculiaruc** [comment]
Alright
