### ISSUE TITLE
Settings-Password-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-3#7]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221154730-9aba4d85-11f0-4887-941f-969d8b95e03a.png)
![image](https://user-images.githubusercontent.com/35475543/221156089-4810e2dc-3bde-4a0d-9abd-30600ee008f4.png)

**Comment by eliudfromkenya** [comment]
I will take this
